{% set version = "2.36" %}

package:
    name: libuuid
    version: {{ version }}

source:
    fn: libuuid-{{ version }}.tar.gz
    url: https://sourceforge.mirrorservice.org/l/li/libuuid/libuuid-{{ version }}.tar.gz
    sha256: dd099ce1432d4877105fdc9dc4b2e68b726db5c777e7907ffd69c6e877824459

build:
    number: 2
    skip: True  # [win]
    run_exports:
      # no info on abi lab.  Leaving defaults.
      - {{ pin_subpackage('libuuid') }}

requirements:
    build:
        # No compiler for osx since this is a build requirement of the osx compiler
        - {{ compiler('c') }}  # [linux]

test:
    commands:
        - test -f ${PREFIX}/lib/libuuid.a  # [unix]
        - conda inspect linkages libuuid  # [unix]

about:
    home: http://sourceforge.net/projects/libuuid/
    license: BSD 3-Clause
    summary: 'Portable uuid C library.'

extra:
    recipe-maintainers:
        - ocefpaf
