package:
    name: libuuid
    version: 1.0.3

source:
    url: ftp://ftp.nersc.no/pub/Aleks/libuuid-1.0.3.tar.gz
    fn: libuuid-1.0.3.tar.gz

build:
    number: 0
    skip: True  # [win]


requirements:
    run:
        - libgcc

test:
    commands:
        - test -f ${PREFIX}/lib/libuuid.a  # [unix]
        - conda inspect linkages -n _test libuuid  # [linux]

about:
    home: http://sourceforge.net/projects/libuuid/
    license: BSD
    summary: Portable uuid C library

extra:
    recipe-maintainers:
        - ocefpaf
